name: pujili_vive
description: "App móvil de turismo para promocionar Pujilí, Cotopaxi."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any

  # State management
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5

  # Functional error handling
  dartz: ^0.10.1

  # Dependency injection
  get_it: ^9.2.1

  # Maps
  google_maps_flutter: ^2.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  bloc_test: ^9.1.7
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/data/
    - assets/images/
